[package]
name = "slate"
version = "0.0.0"
edition = "2024"

[build-dependencies]
#TODO

[dev-dependencies]
anyhow = { workspace = true }

#---
[workspace]
members = [
    "packages/core",
    "packages/schema",
    "packages/sdk",
    "services/auth",
    "services/content",
    "services/location",
    "services/map",
    "services/debug",
    "services/monitor",
    "services/feed",
]

[workspace.dependencies]
anyhow = { version = "1.0" }
chrono = { version = "*" }
clap = { version = "*", default-features = false, features = ["derive"] }
oops = { git = "https://github.com/open-dx/oops-rs", default-features = false }
crwap = { git = "https://github.com/open-dx/oops-rs", default-features = false }
