services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 3904:5678
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=n8n.brainbow.localhost
      - N8N_PORT=5678
      - N8N_HIDE_USAGE_PAGE=true
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.brainbow.localhost/
      - GENERIC_TIMEZONE=America/Los_Angeles
      - TZ=America/Los_Angeles
      - N8N_RESTRICT_FILE_ACCESS_TO=/files
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:
