//! Constructs a `MainWorker` — the shared boilerplate previously duplicated between
//! `ethos-ecma`'s plain `start()` method and its `ffi::c_exec_module` function. Neither the
//! `WorkerServiceOptions` setup nor the bootstrap call itself knows anything about which
//! dialect's extensions or JS bootstrap scripts are being loaded — that's the caller's job,
//! passed in via `extensions`.

use std::path::PathBuf;
use std::rc::Rc;
use std::sync::Arc;

use deno_resolver::npm::DenoInNpmPackageChecker;
use deno_resolver::npm::ManagedNpmResolver;

use deno_runtime::deno_core::Extension;
use deno_runtime::deno_core::FsModuleLoader;
use deno_runtime::deno_core::ModuleSpecifier;
use deno_runtime::deno_fs::RealFs;
use deno_runtime::deno_io::Stdio;
use deno_runtime::deno_permissions::Permissions;
use deno_runtime::deno_permissions::PermissionsContainer;
use deno_runtime::permissions::RuntimePermissionDescriptorParser;
use deno_runtime::worker::MainWorker;
use deno_runtime::worker::WorkerOptions;
use deno_runtime::worker::WorkerServiceOptions;
use deno_runtime::BootstrapOptions;
use deno_runtime::UNSTABLE_FEATURES;

use sys_traits::impls::RealSys;

/// Built by `build.rs` (`deno_runtime::snapshot::create_runtime_snapshot`). Deno-generic — it
/// only bakes in deno's own base extensions (`deno_telemetry`, etc.), not any dialect's. Without
/// this, those extensions fall back to loading their raw, unbundled TypeScript source at
/// runtime, which V8 can't parse.
pub static DEFAULT_SNAPSHOT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/DENO_SNAPSHOT.bin"));

// `RESIDUAL_LAZY_ESM_SOURCES`/`RESIDUAL_LAZY_JS_SOURCES` — generated by `build.rs` alongside
// `DEFAULT_SNAPSHOT` above; see its own doc comment for why these exist (the `lazy_loaded_*`
// files `create_runtime_snapshot` didn't manage to bake into the snapshot blob itself still need
// their raw source available somewhere in the binary, or a script calling e.g. `fetch()` fails at
// runtime with "cannot be lazy-loaded as it was not included in the binary").
include!(concat!(env!("OUT_DIR"), "/residual_lazy_sources.rs"));

/// Bootstraps a `MainWorker` ready to execute `main_module`. Must be called from within an
/// active Tokio runtime context (e.g. inside `tokio::runtime::Runtime::block_on`) — bootstrapping
/// runs the worker's own bootstrap script, which sets up Node-compat globals including
/// `process.stdout`/`stdin` TTY wrapping, an op that needs a live Tokio reactor. Calling this
/// outside one panics with "there is no reactor running".
pub fn bootstrap_main_worker(
    main_module: &ModuleSpecifier,
    stdio: Stdio,
    origin_storage_dir: Option<PathBuf>,
    extensions: Vec<Extension>,
    should_wait_for_inspector_session: bool,
    startup_snapshot: Option<&'static [u8]>,
) -> MainWorker {
    // deno_fetch's client is TLS-capable even for plain http:// requests, and rustls 0.23 panics
    // on first use if no process-level CryptoProvider was installed. install_default() errors if
    // one is already installed, which is fine to ignore.
    let _ = rustls::crypto::ring::default_provider().install_default();

    let mut feature_checker = deno_runtime::FeatureChecker::default();
    for feature in UNSTABLE_FEATURES {
        feature_checker.enable_feature(feature.name);
    }

    let worker_service_options = WorkerServiceOptions::<DenoInNpmPackageChecker, ManagedNpmResolver<RealSys>, RealSys> {
        deno_rt_native_addon_loader: None,
        module_loader: Rc::new(FsModuleLoader),
        permissions: PermissionsContainer::new(
            Arc::new(RuntimePermissionDescriptorParser::new(RealSys)),
            Permissions::allow_all(),
        ),
        blob_store: Arc::new(deno_runtime::deno_web::BlobStore::default()),
        broadcast_channel: Default::default(),
        feature_checker: Arc::new(feature_checker),
        node_services: Default::default(),
        npm_process_state_provider: Default::default(),
        root_cert_store_provider: Default::default(),
        fetch_dns_resolver: Default::default(),
        shared_array_buffer_store: Default::default(),
        compiled_wasm_module_store: Default::default(),
        v8_code_cache: Default::default(),
        fs: Arc::new(RealFs),
        bundle_provider: None,
    };

    let unstable_features = UNSTABLE_FEATURES.iter().map(|feature| feature.id).collect();

    MainWorker::bootstrap_from_options(
        main_module,
        worker_service_options,
        WorkerOptions {
            stdio,
            bootstrap: BootstrapOptions { unstable_features, ..Default::default() },
            origin_storage_dir,
            extensions,
            should_wait_for_inspector_session,
            startup_snapshot: startup_snapshot.or(Some(DEFAULT_SNAPSHOT)),
            residual_lazy_esm_sources: RESIDUAL_LAZY_ESM_SOURCES,
            residual_lazy_js_sources: RESIDUAL_LAZY_JS_SOURCES,
            ..Default::default()
        },
    )
}

/// The `ethos_core::Runtime` implementation for JS/TS. Deliberately the simple half of what this
/// crate can do — a bare `JsRuntime` executing raw source text and returning its last
/// expression's value, no module resolution, no extensions, no FFI. The richer module-execution
/// path (`bootstrap_main_worker` above, and the `ffi`/`runtime` modules built on it) stays
/// available directly for callers that need it, like `ethos-cli`'s `run-command`.
#[derive(Default)]
pub struct DenoRuntime;

impl ethos_core::Runtime for DenoRuntime {
    type Error = deno_core::error::CoreError;

    fn execute(&mut self, source: &str) -> Result<String, Self::Error> {
        let tokio_runtime = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("failed to build a Tokio runtime");

        tokio_runtime.block_on(async move {
            let mut js_runtime = deno_core::JsRuntime::new(deno_core::RuntimeOptions::default());

            let result = js_runtime.execute_script("<source>", source.to_string())?;

            js_runtime.run_event_loop(deno_core::PollEventLoopOptions::default()).await?;

            deno_core::scope!(scope, js_runtime);
            let local = deno_core::v8::Local::new(scope, result);
            Ok(local.to_rust_string_lossy(scope))
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ethos_core::Runtime;

    #[test]
    fn executes_js_source_and_returns_its_value() {
        let mut runtime = DenoRuntime;
        let output = runtime.execute("1 + 2").expect("execute should succeed");
        assert_eq!(output, "3");
    }
}
