edition = "2024"
style_edition = "2024"
unstable_features = true

max_width = 120

merge_derives = false

use_small_heuristics = "Off"

imports_granularity = "Item"

chain_width = 80

array_width = 40

match_block_trailing_comma = false

reorder_imports = true

wrap_comments = false

format_strings = false

normalize_comments = false

match_arm_blocks = false
