[template]
name = "service"
include = [
    "Cargo.toml",
    "src/**/*.rs",
    "deno.json",
    "scripts/**/*.tsx",
    "lib/**/*.dart",
    "pubspec.yaml",
    "web/**/*.html",
    "README.md",
]
# .. or
# exclude = [
#     ".output/",
#     ".scratch/",
# ]

[hooks.generate]
command = "deno run -A scripts/.init.tsx"

# [hooks.error]
# command = "deno run scripts/.cleanup.tsx"
