// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Unity.Runtime
{
    public static unsafe partial class EcmaRuntime
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "libecma";
#endif
        



        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void c_verify_log_callback__cb_delegate(byte* message);



        /// <summary>
        ///  Initialize a global static `EcmaRuntime`` instance.
        ///
        ///  Use this when you want to create a single, managed instance of Deno's
        ///    `MainWorker` for use in another managed environment.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aby__bootstrap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CBootstrapResult c_bootstrap(CBootstrapOptions options);

        [DllImport(__DllName, EntryPoint = "aby__verify_log_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void c_verify_log_callback(c_verify_log_callback__cb_delegate _cb);

        [DllImport(__DllName, EntryPoint = "ecma__construct_runtime", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CEcmaRuntime* c_construct_runtime(CEcmaRuntimeConfig config);

        [DllImport(__DllName, EntryPoint = "ecma__send_broadcast", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void c_send_broadcast(CEcmaRuntime* cself, uint message);

        [DllImport(__DllName, EntryPoint = "ecma__exec_module", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CStartResult c_exec_module(CEcmaRuntime* cself, CExecuteModuleOptions options);

        [DllImport(__DllName, EntryPoint = "ecma__free_runtime", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void c_free_runtime(CEcmaRuntime* obj_ptr);

        [DllImport(__DllName, EntryPoint = "ecma__get_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CEcmaRuntimeState c_get_state();

        /// <summary>
        ///  TODO: Return a CEcmaRuntimeStartResult (repr(C)) for state.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "aby__start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CStartResult c_start(CExecuteModuleOptions options);


    }

    /// <summary>
    ///  TODO
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CBootstrapOptions
    {
        public byte* thread_prefix;
        public CEcmaRuntimeConfig ecma_runtime_config;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEcmaRuntime
    {
        public CEcmaRuntimeConfig config;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CEcmaRuntimeConfig
    {
        [MarshalAs(UnmanagedType.U1)] public bool inspector_wait;
        public ushort inspector_port;
        public byte* db_dir;
        public byte* log_dir;
        public CEcmaRuntimeLogLevel log_level;
        public void* log_callback_fn;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CExecuteModuleOptions
    {
        public byte* main_module_specifier;
    }


    public enum CBootstrapResult : uint
    {
        Ok = 0,
        UnknownError = 1,
        EcmaRuntimeMissing = 2,
        EcmaRuntimeFailed = 3,
        LogCaptureFailed = 4,
    }

    public enum CEcmaRuntimeLogLevel : uint
    {
        None = 0,
        Error = 1,
        Warning = 2,
        Info = 3,
        Debug = 4,
        Trace = 5,
    }

    /// <summary>
    ///  Representing the state of the current `EcmaRuntime`` instance
    ///  running in the bound process.
    ///
    ///  Tagged repr(C) for ffi to Unity, Unreal, etc.
    /// </summary>
    public enum CEcmaRuntimeState : uint
    {
        /// <summary>
        ///  No state has been set, yet. Treat this as "uninitialized".
        /// </summary>
        None = 0,
        /// <summary>
        ///  Runtime has been bootstrapped but not yet "warm" (running).
        /// </summary>
        Cold = 1,
        /// <summary>
        ///  The runtime is executing startup operations. Try again next frame.
        /// </summary>
        Startup = 2,
        /// <summary>
        ///  The runtime is working and has had no problems (yet).
        ///  Check later for failures, but all good so far!
        /// </summary>
        Warm = 3,
        /// <summary>
        ///  The runtime failed in a predictable way. The host is free to attempt
        ///  to recover. Otherwise, shut down gracefully.
        /// </summary>
        Failed = 4,
        /// <summary>
        ///  The runtime encountered an unrecoverable error. The runtime should
        ///  shutdown completely before trying again or bad things can happen.
        /// </summary>
        Panic = 5,
        /// <summary>
        ///  The runtime has quit for some reason.
        /// </summary>
        Shutdown = 6,
    }

    /// <summary>
    ///  TODO
    /// </summary>
    public enum CStartResult : uint
    {
        Ok = 0,
        Err = 1,
        BindingErr = 2,
        EcmaRuntimeErr = 3,
        FailedCreateAsyncRuntime = 4,
        FailedFetchingWorkDirErr = 5,
        DataDirInvalidErr = 6,
        LogDirInvalidErr = 7,
        MainModuleInvalidErr = 8,
        MainModuleUninitializedErr = 9,
        FailedModuleExecErr = 10,
        FailedEventLoopErr = 11,
    }


}
