use core::fmt::Debug;
use core::hash::Hasher;

use alloc::boxed::Box;
use alloc::vec::Vec;

use dyn_clone::DynClone;

use crate::element::content::Content;
use crate::scaffold::Scaffold;
use crate::scaffold::ScaffoldError;
use crate::style::ComputedStyles;
use crate::surface::SurfaceUpdate;

/// Re-exported for convenience when importing `Element`
pub use crate::macros::Element;

//---
/// Represents an item that can be drawn on a Surface.
pub trait Element: DynClone + Debug + Send + Sync {
    /// Every element must have a unique identifier. This is typically
    /// auto-generated by the ElementNode upon creation but can be implemented
    /// directly for special cases.
    fn uuid(&self) -> Option<UUID> {
        None
    }

    /// Elements can provide a set of default meta values.
    fn meta(&self) -> Option<()> {
        None
    }

    fn content(&self) -> Option<Content<'_>> {
        None
    }

    #[inline(always)]
    fn draw(&self) -> DrawFn {
        #[inline(always)]
        |_| Ok(())
    }
}

//---
/// TODO
pub trait ElementIndex: Copy + Clone + Debug + PartialEq + Eq + PartialOrd + Ord {
    //.
}

#[derive(Clone, Default, Debug)]
pub struct ElementHasher {
    hasher: ahash::AHasher,
}

impl ElementHasher {
    pub fn new() -> Self {
        ElementHasher::default()
    }
}

impl Hasher for ElementHasher {
    fn finish(&self) -> u64 {
        self.hasher.finish()
    }

    fn write(&mut self, bytes: &[u8]) {
        self.hasher.write(bytes);
    }
}

//---
/// Style preference for working with UUIDs internally.
pub use uuid::Uuid as UUID;

/// TODO
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct UXID(UUID);

impl ElementIndex for UXID {
    //..
}

//---
/// Wraps an ElementNode in the Scaffold'surface node graph.
pub struct ElementNode<'element> {
    /// The uuid for this instance of an Element on a Surface.
    uuid: UXID, // TODO

    /// The inner element stored in a Scaffold'surface Element graph.
    element: Option<Box<dyn Element + 'element>>,

    // /// The parent node of this node.
    // events: Vec<Box<EventPin>>,

    // /// The parent node of this node.
    // events_v2: HashMap<TypeId, Vec<EventHandler>>,
    /// The parent node of this node.
    stylesheet: ComputedStyles<'element>,

    /// A hash of the element's value.
    hash: u64,
}

impl<'element> ElementNode<'element> {
    /// Create a new instance of an ElementNode using the global allocator.
    ///
    /// If the the element doesn't exist or doesn't provide a uuid, a new one
    /// is generated for the current node.
    pub fn new(element: Option<Box<dyn Element + 'element>>) -> Self {
        // Attempt to get the uuid from the element or generate a new one.
        let uuid = match element.as_ref() {
            Some(element) => match element.uuid() {
                Some(uuid) => UXID(uuid),
                None => UXID(UUID::new_v4()),
            },

            // If the element doesn't exist, generate a new uuid.
            None => UXID(UUID::default()),
        };

        ElementNode {
            uuid,
            element,
            // events: Vec::new(),
            // events_v2: HashMap::new(),
            stylesheet: ComputedStyles::new(),
            hash: 0,
        }
    }
}

impl core::fmt::Display for ElementNode<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "ElementNode#{}", self.uxid().0)
    }
}

impl core::fmt::Debug for ElementNode<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("ElementNode#TODO")
            .finish()
    }
}

impl<'element> ElementNode<'element> {
    pub fn uxid(&self) -> UXID {
        self.uuid
    }

    /// TODO: Make this private?
    pub fn uuid(&self) -> UUID {
        self.uuid.0
    }

    pub fn hash(&self) -> u64 {
        self.hash
    }

    pub fn set_hash(&mut self, hash: u64) {
        #[cfg(feature = "verbose")]
        tracing::debug!("Setting hash for {:} to {:}", self, hash);
        self.hash = hash;
    }

    pub fn element(&self) -> Option<&dyn Element> {
        self.element
            .as_ref()
            .map(|element| &**element)
    }

    pub fn element_mut(&'element mut self) -> Option<&'element mut dyn Element> {
        self.element
            .as_mut()
            .map(move |element| &mut **element)
    }

    pub fn set_element(&mut self, element: Option<Box<dyn Element + 'element>>) {
        self.element = element;
    }

    pub fn alt(&self) -> Option<&str> {
        Some("TODO")
    }

    pub fn content(&self) -> Option<Content<'_>> {
        self.element
            .as_ref()
            .and_then(|e| e.content())
    }

    pub fn stylesheet(&self) -> &ComputedStyles<'element> {
        &self.stylesheet
    }

    pub fn stylesheet_mut(&mut self) -> &mut ComputedStyles<'element> {
        &mut self.stylesheet
    }
}

//---
/// TODO
#[derive(Copy, Clone, Debug)]
pub enum ElementNodeRel {
    Parent,

    Child,
}

//---
/// TODO
#[derive(Debug)]
pub enum ElementError {
    Unknown(&'static str),
}

impl From<&'static str> for ElementError {
    fn from(error: &'static str) -> Self {
        ElementError::Unknown(error)
    }
}

// TODO: Remove this when we bring back oops.
#[automatically_derived]
impl core::error::Error for ElementError {}

// TODO: Remove this when we bring back oops.
#[automatically_derived]
impl core::fmt::Display for ElementError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            ElementError::Unknown(error) => write!(f, "TerminalError::Unknown: {:}", error),
        }
    }
}

pub type DrawFn = fn(&mut Scaffold<'_>) -> Result<(), ScaffoldError>;

/// TODO
#[derive(Default, Debug)]
pub enum DrawReport {
    Success(Vec<SurfaceUpdate>),

    #[default]
    Noop,
}

//---
pub mod tests {
    use super::Element;
    use super::UUID;

    //---
    /// Example implementation of the Element type.
    ///
    /// TODO: Make this private once Chalk provides some elements for examples.
    #[derive(Element, Default, Clone, Hash, Debug)]
    pub struct BaselineElementMock {
        /// The display name for the test element instance.
        #[prop(name: Into<String>)] // TODO
        name: Option<alloc::string::String>,

        /// An arbitrary numeric field for testing state change detection.
        number: usize,
    }

    #[automatically_derived]
    impl BaselineElementMock {
        /// Set the name of the Element.
        /// TODO: Auto-generated for each #[prop] when not supplied.
        pub fn with_name<N: Into<alloc::string::String>>(mut self, name: N) -> Self {
            self.name = Some(name.into());
            self // etc..
        }
    }

    impl BaselineElementMock {
        /// Implemented by one of the following scenarios:
        /// - The developer defines a `#[uuid]` attribute on the struct.
        /// - The developer defines a `#[uuid]` attribute on a field.
        /// - The developer defines a `#[prop(uuid)]` attribute.
        /// - The developer defines a `with_uuid(..)` method.
        ///
        /// TODO: Evaluate this for safety (lol).
        pub fn with_uuid(self, _uuid: UUID) -> Self {
            // tracing::debug!("TODO: Apply custom UUID {:}!", _uuid);
            self // etc..
        }

        /// Props can also be defined by the developer explicitly for greater
        /// control over the element's inputs.
        pub fn with_number(mut self, number: usize) -> Self {
            self.number = number;
            self // etc..
        }
    }

    impl BaselineElementMock {
        pub fn name(&self) -> Option<&str> {
            self.name
                .as_ref()
                .map(|name| name.as_str())
        }

        pub fn number(&self) -> usize {
            self.number
        }
    }

    // impl ElementTestImpl {
    //     /// The `chizel::render` attribute is used to generate a render function
    //     /// for the element using the `chizel::uix!` macro. It does a number of
    //     /// things, including simplifying the method signature.
    //     ///
    //     /// Note: Until this is implemented, the `chizel::render` attribute is just
    //     ///   throwing it all away (you can't call it).
    //     ///
    //     /// Use this space to freely design the render api.
    //     // #[chizel::render]
    //     fn render<E: Element>(&self, _children: &[E]) -> DrawFn {
    //         chizel::uix! {
    //             <ElementTestImpl name="First Child of ElementTestImpl">
    //                 <ElementTestImpl name="First Child of First Child of ElementTestImpl" />
    //                 <ElementTestImpl name="Second Child of First Child of ElementTestImpl" />
    //                 // {_children}
    //             </ElementTestImpl>
    //         }
    //     }
    // }

    #[test]
    fn test_element() {
        let element = BaselineElementMock::default()
            .with_uuid(UUID::new_v4())
            .with_name("Test Element")
            .with_number(42);

        // Assert that the uuid gets set.
        // assert_ne!(element.uuid(), Some(UUID::default()));
        assert_eq!(element.uuid(), None);

        // Assert that the name gets set.
        assert_eq!(element.name(), Some("Test Element"));

        // Assert that the number gets set.
        assert_eq!(element.number, 42);
    }
}
