[package]
name = "escher-vscode"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]
std = ["escher/std", "tracing-subscriber"]
dev = []
verbose = []
profiling = []

#---
[dependencies]
escher = { workspace = true }

tracing-subscriber = { workspace = true, optional = true }


#--
[dev-dependencies]
clap = { workspace = true, features = ["std", "derive", "color", "help", "usage"] }

tracing-subscriber = { workspace = true, features = ["std", "env-filter", "fmt", "ansi"] }

tokio = { workspace = true, features = ["full"] }

axum = { workspace = true, features = ["tokio", "http1", "http2", "json", "query", "form", "multipart", "matched-path", "original-uri", "macros", "tower-log", "tracing"] }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["full"] }
