services:

  meta:
    profiles: [web, dev]
    build:
      context: ./services/meta
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./services/meta
          target: /workspace/services/meta
          action: sync+restart
        - path: .
          target: /workspace
          action: sync+restart
    ports:
      - "8000:8000"

  www:
    profiles: [web, dev]
    build:
      context: ./services/www
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./services/www
          target: /workspace/services/www
          action: sync+restart
        - path: .
          target: /workspace
          action: sync+restart
    ports:
      - "8100:8000"

  sketch:
    profiles: [web, dev]
    build:
      context: ./services/sketch
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./services/sketch
          target: /workspace/services/sketch
          action: sync+restart
        - path: .
          target: /workspace
          action: sync+restart
    ports:
      - "3000:3000"

  dev:
    profiles: [web, dev]
    build:
      context: ./services/etch-io
      dockerfile: Dockerfile
    ports:
      - "8220:8000"
  
  admin:
    profiles: [web, dev]
    build:
      context: ./services/etch-io
      dockerfile: Dockerfile
    ports:
      - "8230:8000"
  
  db0:
    profiles: [web, dev]
    build:
      context: ./services/etch-io
      dockerfile: Dockerfile
    ports:
      - "9090:8000"
  
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    profiles: [dev]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain
      - DEFAULT_WORKSPACE=/brainbow/projects/slate
      - PWA_APPNAME=brainbow-code-server
    volumes:
      - .:/brainbow/projects/slate
    ports:
      - 3900:8443
    restart: unless-stopped

networks:
  default:
    # You can configure custom networks here if needed.
    # For a basic setup, the default bridge network is usually sufficient.
    # driver: bridge