[package]
name = "slate-sketch"
version = "0.0.0"
edition = "2024"
build = "scripts/build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["std", "ecma"]
std = ["tracing-subscriber"]
dev = []
verbose = []
profiling = []
ecma = []

#---
[dependencies]
slate-core = { workspace = true }
atlas = { workspace = true }

uuid = { workspace = true, features = ["v4"] }

parking_lot = { workspace = true }

derive_more = { workspace = true, features = [
    "from",
    "display",
    "index",
    "index_mut",
    "deref",
    "deref_mut",
    "is_variant",
] }
enum_dispatch = { workspace = true }

num-traits = { workspace = true }

hashbrown = { workspace = true, features = [
    "core",
    "alloc",
    "default-hasher",
    "serde",
    "nightly",
    "rayon",
] }

bumpalo = { workspace = true, features = [
    "allocator_api",
    "boxed",
    "collections",
] }
bumpalo-herd = { workspace = true }

tracing = { workspace = true }
tracing-core = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }

oops = { workspace = true, features = ["macros"] }
eyre = { workspace = true }
color-eyre = { workspace = true }
wasm-bindgen = { version = "0.2.105", default-features = false }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
slate-terminal = { workspace = true }
ratatui = { workspace = true, features = ["crossterm"] }
crossterm = { workspace = true, features = ["events", "bracketed-paste"] }
ansi-to-tui = { workspace = true }

[target.'cfg(target_arch="wasm32")'.dependencies]
uuid = { workspace = true, features = ["v4", "js"] }

[target.'cfg(target_os="windows")'.dependencies]
crossterm = { workspace = true, features = ["windows"] }

#--
[dev-dependencies]
clap = { workspace = true, features = [
    "std",
    "derive",
    "color",
    "help",
    "usage",
] }

tracing = { workspace = true, features = ["std"] }
tracing-subscriber = { workspace = true, features = [
    "std",
    "env-filter",
    "fmt",
    "ansi",
] }

tokio = { workspace = true, features = ["full"] }

axum = { workspace = true, features = [
    "tokio",
    "http1",
    "http2",
    "json",
    "query",
    "form",
    "multipart",
    "matched-path",
    "original-uri",
    "macros",
    "tower-log",
    "tracing",
] }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["full"] }
